// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7wRjuH4ZlFHinQAlhhQvUMXxcga3nUU',
    appId: '1:111378890347:web:0fe75a2292ca330f6ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    authDomain: 'bookmywarehouse-74817.firebaseapp.com',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
    measurementId: 'G-XSQ0YZNY9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwFrMf1sxdOuQjwPZgvnMV-TOo0lZ778',
    appId: '1:111378890347:android:92f9fd35c4644c536ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdz0kHEgvah5G4J1fOqbMFprw44OFhA5Y',
    appId: '1:111378890347:ios:b38c8676260a6a826ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
    iosBundleId: 'com.example.bookmywarehouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdz0kHEgvah5G4J1fOqbMFprw44OFhA5Y',
    appId: '1:111378890347:ios:b38c8676260a6a826ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
    iosBundleId: 'com.example.bookmywarehouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7wRjuH4ZlFHinQAlhhQvUMXxcga3nUU',
    appId: '1:111378890347:web:77f328ecae8573756ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    authDomain: 'bookmywarehouse-74817.firebaseapp.com',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
    measurementId: 'G-TMYFG6KQ20',
  );

}