// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwFrMf1sxdOuQjwPZgvnMV-TOo0lZ778',
    appId: '1:111378890347:android:bdb4e1f2ee0a929b6ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdz0kHEgvah5G4J1fOqbMFprw44OFhA5Y',
    appId: '1:111378890347:ios:f25cadaf26d3f0ff6ffb2e',
    messagingSenderId: '111378890347',
    projectId: 'bookmywarehouse-74817',
    storageBucket: 'bookmywarehouse-74817.appspot.com',
    androidClientId: '111378890347-fskpi86125b9mdgp5js76mv2sof4k9uq.apps.googleusercontent.com',
    iosClientId: '111378890347-dgalpntsfctul9f6mhis7hnekrfj7cd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmywarehouse',
  );
}
